Awesome Book Full Page Pull Request
Atril33/Awesome_books pull request #3
Opened 2023-02-22 18:24 UTC by Atril33

**Awesome Books**
This is Awesome Books Project is created with _HTML, CSS & JS_.
This Project has two `<Inputs>` field and one Add ` <button>`.
We Used _JS_ _classes_ in the Project.
We Used `localStorage` Function in this Project.

2023-02-22 22:13 UTC, BenMukebo requested changes
### Hi @Atril33, @peter-akhigbe,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- There is a Navigation bar
- There are three content sections - Books list, Add book form and Contact info. . ✔️ 
- Correclty use the wireframe from the project requirement repo as a guide. ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] Actually you're deplacated the sentence 👇🏻 Kindly remove the first one:

![image](https://user-images.githubusercontent.com/79058364/220769122-1e952b58-fb2e-4c6c-8712-55bd94c739c0.png)

- [ ] Kindly remove the test secion from your README file since we did not write any test on this repo.

![image](https://user-images.githubusercontent.com/79058364/220770175-a6e597cf-9b61-416e-ad57-6c6611f76680.png)


- [ ] I also recommend that you delete the Note: 👇🏻 in your License section as these are instructions on how to complete the License section.


![image](https://user-images.githubusercontent.com/79058364/220769702-9dbcadda-aa00-4d1c-990f-cf6ad4f5c6c9.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Please it will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. Please add descriptive steps from cloning your app to seeing the results displayed on the browser.  This includes `git clone reponameUrl` , `cd repo name` etc


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 04:39 UTC, Shedrack-Sunday requested changes
Hi @Atril33 @peter-akhigbe       👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlights
✅All linters are checked
  
Required Changes ♻️

- [x] Nice efforts so far. The changes needed have to do with a bit of the README. 

_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-23 04:39 UTC, Shedrack-Sunday commented on README.md
> +_we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-
- [ ] As highlighted by the previous reviewer, kindly delete this Note in your License section as these are instructions on how to complete the License section. This keeps your project clean and professional 👍

2023-02-23 05:15 UTC, topeogunleye approved these changes
### Hi @Atril33, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 05:17 UTC, merged